apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-role
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  - services
  - endpoints
  verbs: ["get", "list", "watch"]

# kubectl create clusterrole prometheus-role \
#  --verb=get,list,watch \
#  --resource=pods,nodes,services,endpoints
