apiVersion: v1
kind: Pod
metadata:
  name: arnold-pod
  namespace: training-room-3
spec:
  serviceAccountName: arnold-service-account
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "3600"]
