apiVersion: v1
kind: Pod
metadata:
  name: pod-1-ns-1
  namespace: ns-1
spec:
  serviceAccountName: service-account
  containers:
  - name: kubectl
    image: bitnami/kubectl
    command: ["sleep", "3600"]
