apiVersion: v1
kind: Pod
metadata:
  labels:
    run: img
  name: img
spec:
  containers:
  - image: rajcosivadevops/ustimage
    name: img
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
