apiVersion: v1
kind: Pod
metadata:
  name: podev
  labels:
    app: devpod
  namespace: qa
spec:
  containers:
    - name: m3container002
      image: rajcosivadevops/ustimage
      ports:
        - containerPort: 80
