apiVersion: v1
kind: Pod
metadata:
  name: arun-pod
  namespace: our-class
spec:
  serviceAccountName: find-chris-service-account
  containers:
  - name: find-chris-container
    image: bitnami/kubectl:latest
    command: ['sh', '-c', 'kubectl get pods && kubectl get services']
