apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: our-class
spec:
  serviceAccountName: find-service-account
  containers:
  - name: find-container
    image: bitnami/kubectl:latest
    command: ['sh', '-c', 'kubectl get pods && kubectl get services']
