apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: find-role-binding
  namespace: our-class
subjects:
- kind: ServiceAccount
  name: find-service-account
  namespace: our-class
roleRef:
  kind: Role
  name: find-role
  apiGroup: rbac.authorization.k8s.io
